### ISSUE TITLE
SLS gcloud instance went down

### ISSUE THREAD

**Issue by sgroh** [sdhealthconnect/leap-sls#8]
The application runs fine until some error appears in the log, the last one I' ve found was related with the Java Heap Space, so I increment it from 64m to 256m

Error form the log:
2021-08-27T17:04:15.220564Z java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na] at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[na:na] at org.apache.coyote.AbstractProtocol.startAsyncTimeout(AbstractProtocol.java:628) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43] at org.apache.coyote.AbstractProtocol.lambda$start$0(AbstractProtocol.java:612) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43] at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na] at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na] at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.43.jar!/:9.0.43] at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na] Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by sgroh** [comment]
The application after the change is up, I will keep an eye on the logs.
https://sdhc-sls-leap.uc.r.appspot.com/swagger-ui.html
